### PR TITLE
Added Naive Risk Parity Notebook; Also checking to ensure upstream co…

### PR DESCRIPTION
**Pull request by yyashhp**
…nnection is working correctly...

### CODE REVIEW

**Comment by GivyBoy** [comment]
Could you create a folder within research, where you keep your research notebooks? Each person on the team will have his/her own folder.

**Comment by yyashhp** [comment]
Ye
________________________________
From: Anthony Givans ***@***.***>
Sent: Saturday, September 2, 2023 3:49:55 PM
To: GivyBoy/Quant-Portfolio-Tool ***@***.***>
Cc: Patel, Yash ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GivyBoy/Quant-Portfolio-Tool] Added Naive Risk Parity Notebook; Also checking to ensure upstream co… (PR #20)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Could you create a folder within research, where you keep your research notebooks? Each person on the team will have his/her own folder.

**Comment by yyashhp** [comment]
Added my own folder

**Comment by yyashhp** [comment]
deleted dupes

**Comment by GivyBoy** [comment]
Could you also clean up the notebooks? For eg, use markdown instead of adding comments to code cells, have titles, delete blank cells, etc

**Pull request closed without merging**
